@TodoListAPI_HostAddress = http://localhost:5067

GET {{TodoListAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TodoListAPI_HostAddress}}/users/
Accept: application/json

###

POST {{TodoListAPI_HostAddress}}/users/register
Content-Type: application/json
{
  "name": "Yumo",
  "email": "yumo@doe.com",
  "password": "password"
}

###
